### ISSUE TITLE
iteritems() deprecated in Python3.x

### ISSUE THREAD

**Issue by kedoxey** [OpenSourceBrain/AllenInstituteNeuroML#10]
Replace with `items()`

https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/4e8e71f323cbad1ff45795c436a5d8b7da8f0ae1/CellTypesDatabase/models/ParseAll.py#L239

**Comment by sanjayankur31** [comment]
Thanks @kedoxey. Could you please open a PR with the py3 related changes?
