### ISSUE TITLE
Add GitHub actions to test model tuning 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/AllenInstituteNeuroML#14]
Similar to #13, add tests for simple tuning example (to check python dependencies etc.) in https://github.com/OpenSourceBrain/AllenInstituteNeuroML/tree/master/CellTypesDatabase/tune

Summarise steps in README also.

**Comment by anujanegi** [comment]
These tuning options in tuneAllen.py are broken: -quick, -izhquick, -2stage, -izh2stage

**Comment by pgleeson** [comment]
@anujanegi ` python tuneAllen.py  -izhquick ` worked fine for me. Can you check you have the latest versions of pyneuroml, neurotune & pyelectro

**Comment by sanjayankur31** [comment]
> These tuning options in tuneAllen.py are broken: -quick, -izhquick, -2stage, -izh2stage

Also good to note what errors you get please---that way we have a better chance of indicating/diagnosing what the issue may be
