### ISSUE TITLE
Usage of OpenCortex in GLIF neuron parsing

### ISSUE THREAD

**Issue by anujanegi** [OpenSourceBrain/AllenInstituteNeuroML#36]
For parsing GLIF neurons, [parse_glif.py](https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/master/CellTypesDatabase/models/GLIF/parse_glif.py) uses [opencortex](https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/master/CellTypesDatabase/models/GLIF/parse_glif.py).

Should I completely refactor? @pgleeson @sanjayankur31

**Comment by pgleeson** [comment]
Yes, probably best... OpenCortex is not defunct, but much of that functionality is present in NeuroMLlte now (see https://github.com/OpenSourceBrain/OpenCortex/tree/master/examples/neuromllite), and that's a better way to generate the files longer term.

First step though would be to make sure the existing scripts still work with OC & add tests to regen, which can be updated...

**Comment by anujanegi** [comment]
fixed in #37
