### ISSUE TITLE
AllenSDK load_description() compatibility

### ISSUE THREAD

**Issue by kedoxey** [OpenSourceBrain/AllenInstituteNeuroML#7]
A dictionary is required for the input parameters instead of just a string:
    Parameters
    ----------
    args_dict : dict
        Parsed arguments dictionary with following keys.
        
        manifest_file : string
            .json file with containing the experiment configuration
        axon_type : string
            Axon handling for the all-active models

https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/4e8e71f323cbad1ff45795c436a5d8b7da8f0ae1/CellTypesDatabase/models/ParseAll.py#L56

**Comment by pgleeson** [comment]
@kedoxey The latest commits fix this and other issues with scripts in the models folder. Try them out and let me know if you have any issue.

**Comment by kedoxey** [comment]
@pgleeson just tested and no issues
